// Auto-generated barrel file - do not edit manually
// Generated by scripts/generate-icons.mjs

// Icons
export {
  AcademicCapIcon,
  AcademicCapIcon as AcademicCap,
} from "./icons/academic-cap";
export {
  AdjustmentsHorizontalIcon,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontal,
} from "./icons/adjustments-horizontal";
export {
  AdjustmentsVerticalIcon,
  AdjustmentsVerticalIcon as AdjustmentsVertical,
} from "./icons/adjustments-vertical";
export {
  ArchiveBoxIcon,
  ArchiveBoxIcon as ArchiveBox,
} from "./icons/archive-box";
export {
  ArchiveBoxArrowDownIcon,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDown,
} from "./icons/archive-box-arrow-down";
export {
  ArchiveBoxXMarkIcon,
  ArchiveBoxXMarkIcon as ArchiveBoxXMark,
} from "./icons/archive-box-x-mark";
export { ArrowDownIcon, ArrowDownIcon as ArrowDown } from "./icons/arrow-down";
export {
  ArrowDownCircleIcon,
  ArrowDownCircleIcon as ArrowDownCircle,
} from "./icons/arrow-down-circle";
export {
  ArrowDownLeftIcon,
  ArrowDownLeftIcon as ArrowDownLeft,
} from "./icons/arrow-down-left";
export {
  ArrowDownOnSquareIcon,
  ArrowDownOnSquareIcon as ArrowDownOnSquare,
} from "./icons/arrow-down-on-square";
export {
  ArrowDownOnSquareStackIcon,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStack,
} from "./icons/arrow-down-on-square-stack";
export {
  ArrowDownRightIcon,
  ArrowDownRightIcon as ArrowDownRight,
} from "./icons/arrow-down-right";
export {
  ArrowDownTrayIcon,
  ArrowDownTrayIcon as ArrowDownTray,
} from "./icons/arrow-down-tray";
export { ArrowLeftIcon, ArrowLeftIcon as ArrowLeft } from "./icons/arrow-left";
export {
  ArrowLeftCircleIcon,
  ArrowLeftCircleIcon as ArrowLeftCircle,
} from "./icons/arrow-left-circle";
export {
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftEndOnRectangleIcon as ArrowLeftEndOnRectangle,
} from "./icons/arrow-left-end-on-rectangle";
export {
  ArrowLeftStartOnRectangleIcon,
  ArrowLeftStartOnRectangleIcon as ArrowLeftStartOnRectangle,
} from "./icons/arrow-left-start-on-rectangle";
export {
  ArrowLongDownIcon,
  ArrowLongDownIcon as ArrowLongDown,
} from "./icons/arrow-long-down";
export {
  ArrowLongLeftIcon,
  ArrowLongLeftIcon as ArrowLongLeft,
} from "./icons/arrow-long-left";
export {
  ArrowLongRightIcon,
  ArrowLongRightIcon as ArrowLongRight,
} from "./icons/arrow-long-right";
export {
  ArrowLongUpIcon,
  ArrowLongUpIcon as ArrowLongUp,
} from "./icons/arrow-long-up";
export { ArrowPathIcon, ArrowPathIcon as ArrowPath } from "./icons/arrow-path";
export {
  ArrowPathRoundedSquareIcon,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquare,
} from "./icons/arrow-path-rounded-square";
export {
  ArrowRightIcon,
  ArrowRightIcon as ArrowRight,
} from "./icons/arrow-right";
export {
  ArrowRightCircleIcon,
  ArrowRightCircleIcon as ArrowRightCircle,
} from "./icons/arrow-right-circle";
export {
  ArrowRightEndOnRectangleIcon,
  ArrowRightEndOnRectangleIcon as ArrowRightEndOnRectangle,
} from "./icons/arrow-right-end-on-rectangle";
export {
  ArrowRightStartOnRectangleIcon,
  ArrowRightStartOnRectangleIcon as ArrowRightStartOnRectangle,
} from "./icons/arrow-right-start-on-rectangle";
export {
  ArrowTopRightOnSquareIcon,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquare,
} from "./icons/arrow-top-right-on-square";
export {
  ArrowTrendingDownIcon,
  ArrowTrendingDownIcon as ArrowTrendingDown,
} from "./icons/arrow-trending-down";
export {
  ArrowTrendingUpIcon,
  ArrowTrendingUpIcon as ArrowTrendingUp,
} from "./icons/arrow-trending-up";
export {
  ArrowTurnDownLeftIcon,
  ArrowTurnDownLeftIcon as ArrowTurnDownLeft,
} from "./icons/arrow-turn-down-left";
export {
  ArrowTurnDownRightIcon,
  ArrowTurnDownRightIcon as ArrowTurnDownRight,
} from "./icons/arrow-turn-down-right";
export {
  ArrowTurnLeftDownIcon,
  ArrowTurnLeftDownIcon as ArrowTurnLeftDown,
} from "./icons/arrow-turn-left-down";
export {
  ArrowTurnLeftUpIcon,
  ArrowTurnLeftUpIcon as ArrowTurnLeftUp,
} from "./icons/arrow-turn-left-up";
export {
  ArrowTurnRightDownIcon,
  ArrowTurnRightDownIcon as ArrowTurnRightDown,
} from "./icons/arrow-turn-right-down";
export {
  ArrowTurnRightUpIcon,
  ArrowTurnRightUpIcon as ArrowTurnRightUp,
} from "./icons/arrow-turn-right-up";
export {
  ArrowTurnUpLeftIcon,
  ArrowTurnUpLeftIcon as ArrowTurnUpLeft,
} from "./icons/arrow-turn-up-left";
export {
  ArrowTurnUpRightIcon,
  ArrowTurnUpRightIcon as ArrowTurnUpRight,
} from "./icons/arrow-turn-up-right";
export { ArrowUpIcon, ArrowUpIcon as ArrowUp } from "./icons/arrow-up";
export {
  ArrowUpCircleIcon,
  ArrowUpCircleIcon as ArrowUpCircle,
} from "./icons/arrow-up-circle";
export {
  ArrowUpLeftIcon,
  ArrowUpLeftIcon as ArrowUpLeft,
} from "./icons/arrow-up-left";
export {
  ArrowUpOnSquareIcon,
  ArrowUpOnSquareIcon as ArrowUpOnSquare,
} from "./icons/arrow-up-on-square";
export {
  ArrowUpOnSquareStackIcon,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStack,
} from "./icons/arrow-up-on-square-stack";
export {
  ArrowUpRightIcon,
  ArrowUpRightIcon as ArrowUpRight,
} from "./icons/arrow-up-right";
export {
  ArrowUpTrayIcon,
  ArrowUpTrayIcon as ArrowUpTray,
} from "./icons/arrow-up-tray";
export {
  ArrowUturnDownIcon,
  ArrowUturnDownIcon as ArrowUturnDown,
} from "./icons/arrow-uturn-down";
export {
  ArrowUturnLeftIcon,
  ArrowUturnLeftIcon as ArrowUturnLeft,
} from "./icons/arrow-uturn-left";
export {
  ArrowUturnRightIcon,
  ArrowUturnRightIcon as ArrowUturnRight,
} from "./icons/arrow-uturn-right";
export {
  ArrowUturnUpIcon,
  ArrowUturnUpIcon as ArrowUturnUp,
} from "./icons/arrow-uturn-up";
export {
  ArrowsPointingInIcon,
  ArrowsPointingInIcon as ArrowsPointingIn,
} from "./icons/arrows-pointing-in";
export {
  ArrowsPointingOutIcon,
  ArrowsPointingOutIcon as ArrowsPointingOut,
} from "./icons/arrows-pointing-out";
export {
  ArrowsRightLeftIcon,
  ArrowsRightLeftIcon as ArrowsRightLeft,
} from "./icons/arrows-right-left";
export {
  ArrowsUpDownIcon,
  ArrowsUpDownIcon as ArrowsUpDown,
} from "./icons/arrows-up-down";
export { AtSymbolIcon, AtSymbolIcon as AtSymbol } from "./icons/at-symbol";
export { BackspaceIcon, BackspaceIcon as Backspace } from "./icons/backspace";
export { BackwardIcon, BackwardIcon as Backward } from "./icons/backward";
export { BanknotesIcon, BanknotesIcon as Banknotes } from "./icons/banknotes";
export { Bars2Icon, Bars2Icon as Bars2 } from "./icons/bars-2";
export { Bars3Icon, Bars3Icon as Bars3 } from "./icons/bars-3";
export {
  Bars3BottomLeftIcon,
  Bars3BottomLeftIcon as Bars3BottomLeft,
} from "./icons/bars-3-bottom-left";
export {
  Bars3BottomRightIcon,
  Bars3BottomRightIcon as Bars3BottomRight,
} from "./icons/bars-3-bottom-right";
export {
  Bars3CenterLeftIcon,
  Bars3CenterLeftIcon as Bars3CenterLeft,
} from "./icons/bars-3-center-left";
export { Bars4Icon, Bars4Icon as Bars4 } from "./icons/bars-4";
export {
  BarsArrowDownIcon,
  BarsArrowDownIcon as BarsArrowDown,
} from "./icons/bars-arrow-down";
export {
  BarsArrowUpIcon,
  BarsArrowUpIcon as BarsArrowUp,
} from "./icons/bars-arrow-up";
export { Battery0Icon, Battery0Icon as Battery0 } from "./icons/battery-0";
export { Battery50Icon, Battery50Icon as Battery50 } from "./icons/battery-50";
export {
  Battery100Icon,
  Battery100Icon as Battery100,
} from "./icons/battery-100";
export { BeakerIcon, BeakerIcon as Beaker } from "./icons/beaker";
export { BellIcon, BellIcon as Bell } from "./icons/bell";
export { BellAlertIcon, BellAlertIcon as BellAlert } from "./icons/bell-alert";
export { BellSlashIcon, BellSlashIcon as BellSlash } from "./icons/bell-slash";
export {
  BellSnoozeIcon,
  BellSnoozeIcon as BellSnooze,
} from "./icons/bell-snooze";
export { BoldIcon, BoldIcon as Bold } from "./icons/bold";
export { BoltIcon, BoltIcon as Bolt } from "./icons/bolt";
export { BoltSlashIcon, BoltSlashIcon as BoltSlash } from "./icons/bolt-slash";
export { BookOpenIcon, BookOpenIcon as BookOpen } from "./icons/book-open";
export { BookmarkIcon, BookmarkIcon as Bookmark } from "./icons/bookmark";
export {
  BookmarkSlashIcon,
  BookmarkSlashIcon as BookmarkSlash,
} from "./icons/bookmark-slash";
export {
  BookmarkSquareIcon,
  BookmarkSquareIcon as BookmarkSquare,
} from "./icons/bookmark-square";
export { BriefcaseIcon, BriefcaseIcon as Briefcase } from "./icons/briefcase";
export { BugAntIcon, BugAntIcon as BugAnt } from "./icons/bug-ant";
export {
  BuildingLibraryIcon,
  BuildingLibraryIcon as BuildingLibrary,
} from "./icons/building-library";
export {
  BuildingOfficeIcon,
  BuildingOfficeIcon as BuildingOffice,
} from "./icons/building-office";
export {
  BuildingOffice2Icon,
  BuildingOffice2Icon as BuildingOffice2,
} from "./icons/building-office-2";
export {
  BuildingStorefrontIcon,
  BuildingStorefrontIcon as BuildingStorefront,
} from "./icons/building-storefront";
export { CakeIcon, CakeIcon as Cake } from "./icons/cake";
export {
  CalculatorIcon,
  CalculatorIcon as Calculator,
} from "./icons/calculator";
export { CalendarIcon, CalendarIcon as Calendar } from "./icons/calendar";
export {
  CalendarDateRangeIcon,
  CalendarDateRangeIcon as CalendarDateRange,
} from "./icons/calendar-date-range";
export {
  CalendarDaysIcon,
  CalendarDaysIcon as CalendarDays,
} from "./icons/calendar-days";
export { CameraIcon, CameraIcon as Camera } from "./icons/camera";
export { ChartBarIcon, ChartBarIcon as ChartBar } from "./icons/chart-bar";
export {
  ChartBarSquareIcon,
  ChartBarSquareIcon as ChartBarSquare,
} from "./icons/chart-bar-square";
export { ChartPieIcon, ChartPieIcon as ChartPie } from "./icons/chart-pie";
export {
  ChatBubbleBottomCenterIcon,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenter,
} from "./icons/chat-bubble-bottom-center";
export {
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterText,
} from "./icons/chat-bubble-bottom-center-text";
export {
  ChatBubbleLeftIcon,
  ChatBubbleLeftIcon as ChatBubbleLeft,
} from "./icons/chat-bubble-left";
export {
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsis,
} from "./icons/chat-bubble-left-ellipsis";
export {
  ChatBubbleLeftRightIcon,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRight,
} from "./icons/chat-bubble-left-right";
export {
  ChatBubbleOvalLeftIcon,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeft,
} from "./icons/chat-bubble-oval-left";
export {
  ChatBubbleOvalLeftEllipsisIcon,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsis,
} from "./icons/chat-bubble-oval-left-ellipsis";
export { CheckIcon, CheckIcon as Check } from "./icons/check";
export {
  CheckBadgeIcon,
  CheckBadgeIcon as CheckBadge,
} from "./icons/check-badge";
export {
  CheckCircleIcon,
  CheckCircleIcon as CheckCircle,
} from "./icons/check-circle";
export {
  ChevronDoubleDownIcon,
  ChevronDoubleDownIcon as ChevronDoubleDown,
} from "./icons/chevron-double-down";
export {
  ChevronDoubleLeftIcon,
  ChevronDoubleLeftIcon as ChevronDoubleLeft,
} from "./icons/chevron-double-left";
export {
  ChevronDoubleRightIcon,
  ChevronDoubleRightIcon as ChevronDoubleRight,
} from "./icons/chevron-double-right";
export {
  ChevronDoubleUpIcon,
  ChevronDoubleUpIcon as ChevronDoubleUp,
} from "./icons/chevron-double-up";
export {
  ChevronDownIcon,
  ChevronDownIcon as ChevronDown,
} from "./icons/chevron-down";
export {
  ChevronLeftIcon,
  ChevronLeftIcon as ChevronLeft,
} from "./icons/chevron-left";
export {
  ChevronRightIcon,
  ChevronRightIcon as ChevronRight,
} from "./icons/chevron-right";
export { ChevronUpIcon, ChevronUpIcon as ChevronUp } from "./icons/chevron-up";
export {
  ChevronUpDownIcon,
  ChevronUpDownIcon as ChevronUpDown,
} from "./icons/chevron-up-down";
export {
  CircleStackIcon,
  CircleStackIcon as CircleStack,
} from "./icons/circle-stack";
export { ClipboardIcon, ClipboardIcon as Clipboard } from "./icons/clipboard";
export {
  ClipboardDocumentIcon,
  ClipboardDocumentIcon as ClipboardDocument,
} from "./icons/clipboard-document";
export {
  ClipboardDocumentCheckIcon,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheck,
} from "./icons/clipboard-document-check";
export {
  ClipboardDocumentListIcon,
  ClipboardDocumentListIcon as ClipboardDocumentList,
} from "./icons/clipboard-document-list";
export { ClockIcon, ClockIcon as Clock } from "./icons/clock";
export { CloudIcon, CloudIcon as Cloud } from "./icons/cloud";
export {
  CloudArrowDownIcon,
  CloudArrowDownIcon as CloudArrowDown,
} from "./icons/cloud-arrow-down";
export {
  CloudArrowUpIcon,
  CloudArrowUpIcon as CloudArrowUp,
} from "./icons/cloud-arrow-up";
export {
  CodeBracketIcon,
  CodeBracketIcon as CodeBracket,
} from "./icons/code-bracket";
export {
  CodeBracketSquareIcon,
  CodeBracketSquareIcon as CodeBracketSquare,
} from "./icons/code-bracket-square";
export { CogIcon, CogIcon as Cog } from "./icons/cog";
export { Cog6ToothIcon, Cog6ToothIcon as Cog6Tooth } from "./icons/cog-6-tooth";
export { Cog8ToothIcon, Cog8ToothIcon as Cog8Tooth } from "./icons/cog-8-tooth";
export {
  CommandLineIcon,
  CommandLineIcon as CommandLine,
} from "./icons/command-line";
export {
  ComputerDesktopIcon,
  ComputerDesktopIcon as ComputerDesktop,
} from "./icons/computer-desktop";
export { CpuChipIcon, CpuChipIcon as CpuChip } from "./icons/cpu-chip";
export {
  CreditCardIcon,
  CreditCardIcon as CreditCard,
} from "./icons/credit-card";
export { CubeIcon, CubeIcon as Cube } from "./icons/cube";
export {
  CubeTransparentIcon,
  CubeTransparentIcon as CubeTransparent,
} from "./icons/cube-transparent";
export {
  CurrencyBangladeshiIcon,
  CurrencyBangladeshiIcon as CurrencyBangladeshi,
} from "./icons/currency-bangladeshi";
export {
  CurrencyDollarIcon,
  CurrencyDollarIcon as CurrencyDollar,
} from "./icons/currency-dollar";
export {
  CurrencyEuroIcon,
  CurrencyEuroIcon as CurrencyEuro,
} from "./icons/currency-euro";
export {
  CurrencyPoundIcon,
  CurrencyPoundIcon as CurrencyPound,
} from "./icons/currency-pound";
export {
  CurrencyRupeeIcon,
  CurrencyRupeeIcon as CurrencyRupee,
} from "./icons/currency-rupee";
export {
  CurrencyYenIcon,
  CurrencyYenIcon as CurrencyYen,
} from "./icons/currency-yen";
export {
  CursorArrowRaysIcon,
  CursorArrowRaysIcon as CursorArrowRays,
} from "./icons/cursor-arrow-rays";
export {
  CursorArrowRippleIcon,
  CursorArrowRippleIcon as CursorArrowRipple,
} from "./icons/cursor-arrow-ripple";
export {
  DevicePhoneMobileIcon,
  DevicePhoneMobileIcon as DevicePhoneMobile,
} from "./icons/device-phone-mobile";
export {
  DeviceTabletIcon,
  DeviceTabletIcon as DeviceTablet,
} from "./icons/device-tablet";
export { DivideIcon, DivideIcon as Divide } from "./icons/divide";
export { DocumentIcon, DocumentIcon as Document } from "./icons/document";
export {
  DocumentArrowDownIcon,
  DocumentArrowDownIcon as DocumentArrowDown,
} from "./icons/document-arrow-down";
export {
  DocumentArrowUpIcon,
  DocumentArrowUpIcon as DocumentArrowUp,
} from "./icons/document-arrow-up";
export {
  DocumentChartBarIcon,
  DocumentChartBarIcon as DocumentChartBar,
} from "./icons/document-chart-bar";
export {
  DocumentCheckIcon,
  DocumentCheckIcon as DocumentCheck,
} from "./icons/document-check";
export {
  DocumentCurrencyBangladeshiIcon,
  DocumentCurrencyBangladeshiIcon as DocumentCurrencyBangladeshi,
} from "./icons/document-currency-bangladeshi";
export {
  DocumentCurrencyDollarIcon,
  DocumentCurrencyDollarIcon as DocumentCurrencyDollar,
} from "./icons/document-currency-dollar";
export {
  DocumentCurrencyEuroIcon,
  DocumentCurrencyEuroIcon as DocumentCurrencyEuro,
} from "./icons/document-currency-euro";
export {
  DocumentCurrencyPoundIcon,
  DocumentCurrencyPoundIcon as DocumentCurrencyPound,
} from "./icons/document-currency-pound";
export {
  DocumentCurrencyRupeeIcon,
  DocumentCurrencyRupeeIcon as DocumentCurrencyRupee,
} from "./icons/document-currency-rupee";
export {
  DocumentCurrencyYenIcon,
  DocumentCurrencyYenIcon as DocumentCurrencyYen,
} from "./icons/document-currency-yen";
export {
  DocumentDuplicateIcon,
  DocumentDuplicateIcon as DocumentDuplicate,
} from "./icons/document-duplicate";
export {
  DocumentMagnifyingGlassIcon,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlass,
} from "./icons/document-magnifying-glass";
export {
  DocumentMinusIcon,
  DocumentMinusIcon as DocumentMinus,
} from "./icons/document-minus";
export {
  DocumentPlusIcon,
  DocumentPlusIcon as DocumentPlus,
} from "./icons/document-plus";
export {
  DocumentTextIcon,
  DocumentTextIcon as DocumentText,
} from "./icons/document-text";
export {
  EllipsisHorizontalIcon,
  EllipsisHorizontalIcon as EllipsisHorizontal,
} from "./icons/ellipsis-horizontal";
export {
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircle,
} from "./icons/ellipsis-horizontal-circle";
export {
  EllipsisVerticalIcon,
  EllipsisVerticalIcon as EllipsisVertical,
} from "./icons/ellipsis-vertical";
export { EnvelopeIcon, EnvelopeIcon as Envelope } from "./icons/envelope";
export {
  EnvelopeOpenIcon,
  EnvelopeOpenIcon as EnvelopeOpen,
} from "./icons/envelope-open";
export { EqualsIcon, EqualsIcon as Equals } from "./icons/equals";
export {
  ExclamationCircleIcon,
  ExclamationCircleIcon as ExclamationCircle,
} from "./icons/exclamation-circle";
export {
  ExclamationTriangleIcon,
  ExclamationTriangleIcon as ExclamationTriangle,
} from "./icons/exclamation-triangle";
export { EyeIcon, EyeIcon as Eye } from "./icons/eye";
export {
  EyeDropperIcon,
  EyeDropperIcon as EyeDropper,
} from "./icons/eye-dropper";
export { EyeSlashIcon, EyeSlashIcon as EyeSlash } from "./icons/eye-slash";
export { FaceFrownIcon, FaceFrownIcon as FaceFrown } from "./icons/face-frown";
export { FaceSmileIcon, FaceSmileIcon as FaceSmile } from "./icons/face-smile";
export { FilmIcon, FilmIcon as Film } from "./icons/film";
export {
  FingerPrintIcon,
  FingerPrintIcon as FingerPrint,
} from "./icons/finger-print";
export { FireIcon, FireIcon as Fire } from "./icons/fire";
export { FlagIcon, FlagIcon as Flag } from "./icons/flag";
export { FolderIcon, FolderIcon as Folder } from "./icons/folder";
export {
  FolderArrowDownIcon,
  FolderArrowDownIcon as FolderArrowDown,
} from "./icons/folder-arrow-down";
export {
  FolderMinusIcon,
  FolderMinusIcon as FolderMinus,
} from "./icons/folder-minus";
export {
  FolderOpenIcon,
  FolderOpenIcon as FolderOpen,
} from "./icons/folder-open";
export {
  FolderPlusIcon,
  FolderPlusIcon as FolderPlus,
} from "./icons/folder-plus";
export { ForwardIcon, ForwardIcon as Forward } from "./icons/forward";
export { FunnelIcon, FunnelIcon as Funnel } from "./icons/funnel";
export { GifIcon, GifIcon as Gif } from "./icons/gif";
export { GiftIcon, GiftIcon as Gift } from "./icons/gift";
export { GiftTopIcon, GiftTopIcon as GiftTop } from "./icons/gift-top";
export { GlobeAltIcon, GlobeAltIcon as GlobeAlt } from "./icons/globe-alt";
export {
  GlobeAmericasIcon,
  GlobeAmericasIcon as GlobeAmericas,
} from "./icons/globe-americas";
export {
  GlobeAsiaAustraliaIcon,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustralia,
} from "./icons/globe-asia-australia";
export {
  GlobeEuropeAfricaIcon,
  GlobeEuropeAfricaIcon as GlobeEuropeAfrica,
} from "./icons/globe-europe-africa";
export { H1Icon, H1Icon as H1 } from "./icons/h1";
export { H2Icon, H2Icon as H2 } from "./icons/h2";
export { H3Icon, H3Icon as H3 } from "./icons/h3";
export {
  HandRaisedIcon,
  HandRaisedIcon as HandRaised,
} from "./icons/hand-raised";
export {
  HandThumbDownIcon,
  HandThumbDownIcon as HandThumbDown,
} from "./icons/hand-thumb-down";
export {
  HandThumbUpIcon,
  HandThumbUpIcon as HandThumbUp,
} from "./icons/hand-thumb-up";
export { HashtagIcon, HashtagIcon as Hashtag } from "./icons/hashtag";
export { HeartIcon, HeartIcon as Heart } from "./icons/heart";
export { HomeIcon, HomeIcon as Home } from "./icons/home";
export {
  HomeModernIcon,
  HomeModernIcon as HomeModern,
} from "./icons/home-modern";
export {
  IdentificationIcon,
  IdentificationIcon as Identification,
} from "./icons/identification";
export { InboxIcon, InboxIcon as Inbox } from "./icons/inbox";
export {
  InboxArrowDownIcon,
  InboxArrowDownIcon as InboxArrowDown,
} from "./icons/inbox-arrow-down";
export {
  InboxStackIcon,
  InboxStackIcon as InboxStack,
} from "./icons/inbox-stack";
export {
  InformationCircleIcon,
  InformationCircleIcon as InformationCircle,
} from "./icons/information-circle";
export { ItalicIcon, ItalicIcon as Italic } from "./icons/italic";
export { KeyIcon, KeyIcon as Key } from "./icons/key";
export { LanguageIcon, LanguageIcon as Language } from "./icons/language";
export { LifebuoyIcon, LifebuoyIcon as Lifebuoy } from "./icons/lifebuoy";
export { LightBulbIcon, LightBulbIcon as LightBulb } from "./icons/light-bulb";
export { LinkIcon, LinkIcon as Link } from "./icons/link";
export { LinkSlashIcon, LinkSlashIcon as LinkSlash } from "./icons/link-slash";
export {
  ListBulletIcon,
  ListBulletIcon as ListBullet,
} from "./icons/list-bullet";
export {
  LockClosedIcon,
  LockClosedIcon as LockClosed,
} from "./icons/lock-closed";
export { LockOpenIcon, LockOpenIcon as LockOpen } from "./icons/lock-open";
export {
  MagnifyingGlassIcon,
  MagnifyingGlassIcon as MagnifyingGlass,
} from "./icons/magnifying-glass";
export {
  MagnifyingGlassCircleIcon,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircle,
} from "./icons/magnifying-glass-circle";
export {
  MagnifyingGlassMinusIcon,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinus,
} from "./icons/magnifying-glass-minus";
export {
  MagnifyingGlassPlusIcon,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlus,
} from "./icons/magnifying-glass-plus";
export { MapIcon, MapIcon as Map } from "./icons/map";
export { MapPinIcon, MapPinIcon as MapPin } from "./icons/map-pin";
export { MegaphoneIcon, MegaphoneIcon as Megaphone } from "./icons/megaphone";
export {
  MicrophoneIcon,
  MicrophoneIcon as Microphone,
} from "./icons/microphone";
export { MinusIcon, MinusIcon as Minus } from "./icons/minus";
export {
  MinusCircleIcon,
  MinusCircleIcon as MinusCircle,
} from "./icons/minus-circle";
export { MoonIcon, MoonIcon as Moon } from "./icons/moon";
export {
  MusicalNoteIcon,
  MusicalNoteIcon as MusicalNote,
} from "./icons/musical-note";
export { NewspaperIcon, NewspaperIcon as Newspaper } from "./icons/newspaper";
export { NoSymbolIcon, NoSymbolIcon as NoSymbol } from "./icons/no-symbol";
export {
  NumberedListIcon,
  NumberedListIcon as NumberedList,
} from "./icons/numbered-list";
export {
  PaintBrushIcon,
  PaintBrushIcon as PaintBrush,
} from "./icons/paint-brush";
export {
  PaperAirplaneIcon,
  PaperAirplaneIcon as PaperAirplane,
} from "./icons/paper-airplane";
export { PaperClipIcon, PaperClipIcon as PaperClip } from "./icons/paper-clip";
export { PauseIcon, PauseIcon as Pause } from "./icons/pause";
export {
  PauseCircleIcon,
  PauseCircleIcon as PauseCircle,
} from "./icons/pause-circle";
export { PencilIcon, PencilIcon as Pencil } from "./icons/pencil";
export {
  PencilSquareIcon,
  PencilSquareIcon as PencilSquare,
} from "./icons/pencil-square";
export {
  PercentBadgeIcon,
  PercentBadgeIcon as PercentBadge,
} from "./icons/percent-badge";
export { PhoneIcon, PhoneIcon as Phone } from "./icons/phone";
export {
  PhoneArrowDownLeftIcon,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeft,
} from "./icons/phone-arrow-down-left";
export {
  PhoneArrowUpRightIcon,
  PhoneArrowUpRightIcon as PhoneArrowUpRight,
} from "./icons/phone-arrow-up-right";
export {
  PhoneXMarkIcon,
  PhoneXMarkIcon as PhoneXMark,
} from "./icons/phone-x-mark";
export { PhotoIcon, PhotoIcon as Photo } from "./icons/photo";
export { PlayIcon, PlayIcon as Play } from "./icons/play";
export {
  PlayCircleIcon,
  PlayCircleIcon as PlayCircle,
} from "./icons/play-circle";
export { PlayPauseIcon, PlayPauseIcon as PlayPause } from "./icons/play-pause";
export { PlusIcon, PlusIcon as Plus } from "./icons/plus";
export {
  PlusCircleIcon,
  PlusCircleIcon as PlusCircle,
} from "./icons/plus-circle";
export { PowerIcon, PowerIcon as Power } from "./icons/power";
export {
  PresentationChartBarIcon,
  PresentationChartBarIcon as PresentationChartBar,
} from "./icons/presentation-chart-bar";
export {
  PresentationChartLineIcon,
  PresentationChartLineIcon as PresentationChartLine,
} from "./icons/presentation-chart-line";
export { PrinterIcon, PrinterIcon as Printer } from "./icons/printer";
export {
  PuzzlePieceIcon,
  PuzzlePieceIcon as PuzzlePiece,
} from "./icons/puzzle-piece";
export { QrCodeIcon, QrCodeIcon as QrCode } from "./icons/qr-code";
export {
  QuestionMarkCircleIcon,
  QuestionMarkCircleIcon as QuestionMarkCircle,
} from "./icons/question-mark-circle";
export { QueueListIcon, QueueListIcon as QueueList } from "./icons/queue-list";
export { RadioIcon, RadioIcon as Radio } from "./icons/radio";
export {
  ReceiptPercentIcon,
  ReceiptPercentIcon as ReceiptPercent,
} from "./icons/receipt-percent";
export {
  ReceiptRefundIcon,
  ReceiptRefundIcon as ReceiptRefund,
} from "./icons/receipt-refund";
export {
  RectangleGroupIcon,
  RectangleGroupIcon as RectangleGroup,
} from "./icons/rectangle-group";
export {
  RectangleStackIcon,
  RectangleStackIcon as RectangleStack,
} from "./icons/rectangle-stack";
export {
  RocketLaunchIcon,
  RocketLaunchIcon as RocketLaunch,
} from "./icons/rocket-launch";
export { RssIcon, RssIcon as Rss } from "./icons/rss";
export { ScaleIcon, ScaleIcon as Scale } from "./icons/scale";
export { ScissorsIcon, ScissorsIcon as Scissors } from "./icons/scissors";
export { ServerIcon, ServerIcon as Server } from "./icons/server";
export {
  ServerStackIcon,
  ServerStackIcon as ServerStack,
} from "./icons/server-stack";
export { ShareIcon, ShareIcon as Share } from "./icons/share";
export {
  ShieldCheckIcon,
  ShieldCheckIcon as ShieldCheck,
} from "./icons/shield-check";
export {
  ShieldExclamationIcon,
  ShieldExclamationIcon as ShieldExclamation,
} from "./icons/shield-exclamation";
export {
  ShoppingBagIcon,
  ShoppingBagIcon as ShoppingBag,
} from "./icons/shopping-bag";
export {
  ShoppingCartIcon,
  ShoppingCartIcon as ShoppingCart,
} from "./icons/shopping-cart";
export { SignalIcon, SignalIcon as Signal } from "./icons/signal";
export {
  SignalSlashIcon,
  SignalSlashIcon as SignalSlash,
} from "./icons/signal-slash";
export { SlashIcon, SlashIcon as Slash } from "./icons/slash";
export { SparklesIcon, SparklesIcon as Sparkles } from "./icons/sparkles";
export {
  SpeakerWaveIcon,
  SpeakerWaveIcon as SpeakerWave,
} from "./icons/speaker-wave";
export {
  SpeakerXMarkIcon,
  SpeakerXMarkIcon as SpeakerXMark,
} from "./icons/speaker-x-mark";
export {
  Square2StackIcon,
  Square2StackIcon as Square2Stack,
} from "./icons/square-2-stack";
export {
  Square3Stack3dIcon,
  Square3Stack3dIcon as Square3Stack3d,
} from "./icons/square-3-stack-3d";
export {
  Squares2x2Icon,
  Squares2x2Icon as Squares2x2,
} from "./icons/squares-2x2";
export {
  SquaresPlusIcon,
  SquaresPlusIcon as SquaresPlus,
} from "./icons/squares-plus";
export { StarIcon, StarIcon as Star } from "./icons/star";
export { StopIcon, StopIcon as Stop } from "./icons/stop";
export {
  StopCircleIcon,
  StopCircleIcon as StopCircle,
} from "./icons/stop-circle";
export {
  StrikethroughIcon,
  StrikethroughIcon as Strikethrough,
} from "./icons/strikethrough";
export { SunIcon, SunIcon as Sun } from "./icons/sun";
export { SwatchIcon, SwatchIcon as Swatch } from "./icons/swatch";
export {
  TableCellsIcon,
  TableCellsIcon as TableCells,
} from "./icons/table-cells";
export { TagIcon, TagIcon as Tag } from "./icons/tag";
export { TicketIcon, TicketIcon as Ticket } from "./icons/ticket";
export { TrashIcon, TrashIcon as Trash } from "./icons/trash";
export { TrophyIcon, TrophyIcon as Trophy } from "./icons/trophy";
export { TruckIcon, TruckIcon as Truck } from "./icons/truck";
export { TvIcon, TvIcon as Tv } from "./icons/tv";
export { UnderlineIcon, UnderlineIcon as Underline } from "./icons/underline";
export { UserIcon, UserIcon as User } from "./icons/user";
export {
  UserCircleIcon,
  UserCircleIcon as UserCircle,
} from "./icons/user-circle";
export { UserGroupIcon, UserGroupIcon as UserGroup } from "./icons/user-group";
export { UserMinusIcon, UserMinusIcon as UserMinus } from "./icons/user-minus";
export { UserPlusIcon, UserPlusIcon as UserPlus } from "./icons/user-plus";
export { UsersIcon, UsersIcon as Users } from "./icons/users";
export { VariableIcon, VariableIcon as Variable } from "./icons/variable";
export {
  VideoCameraIcon,
  VideoCameraIcon as VideoCamera,
} from "./icons/video-camera";
export {
  VideoCameraSlashIcon,
  VideoCameraSlashIcon as VideoCameraSlash,
} from "./icons/video-camera-slash";
export {
  ViewColumnsIcon,
  ViewColumnsIcon as ViewColumns,
} from "./icons/view-columns";
export {
  ViewfinderCircleIcon,
  ViewfinderCircleIcon as ViewfinderCircle,
} from "./icons/viewfinder-circle";
export { WalletIcon, WalletIcon as Wallet } from "./icons/wallet";
export { WifiIcon, WifiIcon as Wifi } from "./icons/wifi";
export { WindowIcon, WindowIcon as Window } from "./icons/window";
export { WrenchIcon, WrenchIcon as Wrench } from "./icons/wrench";
export {
  WrenchScrewdriverIcon,
  WrenchScrewdriverIcon as WrenchScrewdriver,
} from "./icons/wrench-screwdriver";
export { XCircleIcon, XCircleIcon as XCircle } from "./icons/x-circle";
export { XMarkIcon, XMarkIcon as XMark } from "./icons/x-mark";
// Tokens & Provider
export {
  HEROICONS_ANIMATED_CONFIG,
  type HeroiconsAnimatedOptions,
  provideHeroiconsAnimated,
} from "./tokens/provider";
