// Auto-generated icon component map - do not edit manually
import type { Type } from "@angular/core";
import {
  AcademicCapIcon,
  AdjustmentsHorizontalIcon,
  AdjustmentsVerticalIcon,
  ArchiveBoxArrowDownIcon,
  ArchiveBoxIcon,
  ArchiveBoxXMarkIcon,
  ArrowDownCircleIcon,
  ArrowDownIcon,
  ArrowDownLeftIcon,
  ArrowDownOnSquareIcon,
  ArrowDownOnSquareStackIcon,
  ArrowDownRightIcon,
  ArrowDownTrayIcon,
  ArrowLeftCircleIcon,
  ArrowLeftEndOnRectangleIcon,
  ArrowLeftIcon,
  ArrowLeftStartOnRectangleIcon,
  ArrowLongDownIcon,
  ArrowLongLeftIcon,
  ArrowLongRightIcon,
  ArrowLongUpIcon,
  ArrowPathIcon,
  ArrowPathRoundedSquareIcon,
  ArrowRightCircleIcon,
  ArrowRightEndOnRectangleIcon,
  ArrowRightIcon,
  ArrowRightStartOnRectangleIcon,
  ArrowsPointingInIcon,
  ArrowsPointingOutIcon,
  ArrowsRightLeftIcon,
  ArrowsUpDownIcon,
  ArrowTopRightOnSquareIcon,
  ArrowTrendingDownIcon,
  ArrowTrendingUpIcon,
  ArrowTurnDownLeftIcon,
  ArrowTurnDownRightIcon,
  ArrowTurnLeftDownIcon,
  ArrowTurnLeftUpIcon,
  ArrowTurnRightDownIcon,
  ArrowTurnRightUpIcon,
  ArrowTurnUpLeftIcon,
  ArrowTurnUpRightIcon,
  ArrowUpCircleIcon,
  ArrowUpIcon,
  ArrowUpLeftIcon,
  ArrowUpOnSquareIcon,
  ArrowUpOnSquareStackIcon,
  ArrowUpRightIcon,
  ArrowUpTrayIcon,
  ArrowUturnDownIcon,
  ArrowUturnLeftIcon,
  ArrowUturnRightIcon,
  ArrowUturnUpIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BackwardIcon,
  BanknotesIcon,
  Bars2Icon,
  Bars3BottomLeftIcon,
  Bars3BottomRightIcon,
  Bars3CenterLeftIcon,
  Bars3Icon,
  Bars4Icon,
  BarsArrowDownIcon,
  BarsArrowUpIcon,
  Battery0Icon,
  Battery50Icon,
  Battery100Icon,
  BeakerIcon,
  BellAlertIcon,
  BellIcon,
  BellSlashIcon,
  BellSnoozeIcon,
  BoldIcon,
  BoltIcon,
  BoltSlashIcon,
  BookmarkIcon,
  BookmarkSlashIcon,
  BookmarkSquareIcon,
  BookOpenIcon,
  BriefcaseIcon,
  BugAntIcon,
  BuildingLibraryIcon,
  BuildingOffice2Icon,
  BuildingOfficeIcon,
  BuildingStorefrontIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarDateRangeIcon,
  CalendarDaysIcon,
  CalendarIcon,
  CameraIcon,
  ChartBarIcon,
  ChartBarSquareIcon,
  ChartPieIcon,
  ChatBubbleBottomCenterIcon,
  ChatBubbleBottomCenterTextIcon,
  ChatBubbleLeftEllipsisIcon,
  ChatBubbleLeftIcon,
  ChatBubbleLeftRightIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  ChatBubbleOvalLeftIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpDownIcon,
  ChevronUpIcon,
  CircleStackIcon,
  ClipboardDocumentCheckIcon,
  ClipboardDocumentIcon,
  ClipboardDocumentListIcon,
  ClipboardIcon,
  ClockIcon,
  CloudArrowDownIcon,
  CloudArrowUpIcon,
  CloudIcon,
  CodeBracketIcon,
  CodeBracketSquareIcon,
  Cog6ToothIcon,
  Cog8ToothIcon,
  CogIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  CpuChipIcon,
  CreditCardIcon,
  CubeIcon,
  CubeTransparentIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorArrowRaysIcon,
  CursorArrowRippleIcon,
  DevicePhoneMobileIcon,
  DeviceTabletIcon,
  DivideIcon,
  DocumentArrowDownIcon,
  DocumentArrowUpIcon,
  DocumentChartBarIcon,
  DocumentCheckIcon,
  DocumentCurrencyBangladeshiIcon,
  DocumentCurrencyDollarIcon,
  DocumentCurrencyEuroIcon,
  DocumentCurrencyPoundIcon,
  DocumentCurrencyRupeeIcon,
  DocumentCurrencyYenIcon,
  DocumentDuplicateIcon,
  DocumentIcon,
  DocumentMagnifyingGlassIcon,
  DocumentMinusIcon,
  DocumentPlusIcon,
  DocumentTextIcon,
  EllipsisHorizontalCircleIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  EqualsIcon,
  ExclamationCircleIcon,
  ExclamationTriangleIcon,
  EyeDropperIcon,
  EyeIcon,
  EyeSlashIcon,
  FaceFrownIcon,
  FaceSmileIcon,
  FilmIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  FolderArrowDownIcon,
  FolderIcon,
  FolderMinusIcon,
  FolderOpenIcon,
  FolderPlusIcon,
  ForwardIcon,
  FunnelIcon,
  GifIcon,
  GiftIcon,
  GiftTopIcon,
  GlobeAltIcon,
  GlobeAmericasIcon,
  GlobeAsiaAustraliaIcon,
  GlobeEuropeAfricaIcon,
  H1Icon,
  H2Icon,
  H3Icon,
  HandRaisedIcon,
  HandThumbDownIcon,
  HandThumbUpIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  HomeModernIcon,
  IdentificationIcon,
  InboxArrowDownIcon,
  InboxIcon,
  InboxStackIcon,
  InformationCircleIcon,
  ItalicIcon,
  KeyIcon,
  LanguageIcon,
  LifebuoyIcon,
  LightBulbIcon,
  LinkIcon,
  LinkSlashIcon,
  ListBulletIcon,
  LockClosedIcon,
  LockOpenIcon,
  MagnifyingGlassCircleIcon,
  MagnifyingGlassIcon,
  MagnifyingGlassMinusIcon,
  MagnifyingGlassPlusIcon,
  MapIcon,
  MapPinIcon,
  MegaphoneIcon,
  MicrophoneIcon,
  MinusCircleIcon,
  MinusIcon,
  MoonIcon,
  MusicalNoteIcon,
  NewspaperIcon,
  NoSymbolIcon,
  NumberedListIcon,
  PaintBrushIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseCircleIcon,
  PauseIcon,
  PencilIcon,
  PencilSquareIcon,
  PercentBadgeIcon,
  PhoneArrowDownLeftIcon,
  PhoneArrowUpRightIcon,
  PhoneIcon,
  PhoneXMarkIcon,
  PhotoIcon,
  PlayCircleIcon,
  PlayIcon,
  PlayPauseIcon,
  PlusCircleIcon,
  PlusIcon,
  PowerIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzlePieceIcon,
  QrCodeIcon,
  QuestionMarkCircleIcon,
  QueueListIcon,
  RadioIcon,
  ReceiptPercentIcon,
  ReceiptRefundIcon,
  RectangleGroupIcon,
  RectangleStackIcon,
  RocketLaunchIcon,
  RssIcon,
  ScaleIcon,
  ScissorsIcon,
  ServerIcon,
  ServerStackIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SignalIcon,
  SignalSlashIcon,
  SlashIcon,
  SparklesIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  Square2StackIcon,
  Square3Stack3dIcon,
  Squares2x2Icon,
  SquaresPlusIcon,
  StarIcon,
  StopCircleIcon,
  StopIcon,
  StrikethroughIcon,
  SunIcon,
  SwatchIcon,
  TableCellsIcon,
  TagIcon,
  TicketIcon,
  TrashIcon,
  TrophyIcon,
  TruckIcon,
  TvIcon,
  UnderlineIcon,
  UserCircleIcon,
  UserGroupIcon,
  UserIcon,
  UserMinusIcon,
  UserPlusIcon,
  UsersIcon,
  VariableIcon,
  VideoCameraIcon,
  VideoCameraSlashIcon,
  ViewColumnsIcon,
  ViewfinderCircleIcon,
  WalletIcon,
  WifiIcon,
  WindowIcon,
  WrenchIcon,
  WrenchScrewdriverIcon,
  XCircleIcon,
  XMarkIcon,
} from "@heroicons-animated/angular";

export const ICON_COMPONENTS: Record<string, Type<unknown>> = {
  "academic-cap": AcademicCapIcon,
  "adjustments-horizontal": AdjustmentsHorizontalIcon,
  "adjustments-vertical": AdjustmentsVerticalIcon,
  "archive-box": ArchiveBoxIcon,
  "archive-box-arrow-down": ArchiveBoxArrowDownIcon,
  "archive-box-x-mark": ArchiveBoxXMarkIcon,
  "arrow-down": ArrowDownIcon,
  "arrow-down-circle": ArrowDownCircleIcon,
  "arrow-down-left": ArrowDownLeftIcon,
  "arrow-down-on-square": ArrowDownOnSquareIcon,
  "arrow-down-on-square-stack": ArrowDownOnSquareStackIcon,
  "arrow-down-right": ArrowDownRightIcon,
  "arrow-down-tray": ArrowDownTrayIcon,
  "arrow-left": ArrowLeftIcon,
  "arrow-left-circle": ArrowLeftCircleIcon,
  "arrow-left-end-on-rectangle": ArrowLeftEndOnRectangleIcon,
  "arrow-left-start-on-rectangle": ArrowLeftStartOnRectangleIcon,
  "arrow-long-down": ArrowLongDownIcon,
  "arrow-long-left": ArrowLongLeftIcon,
  "arrow-long-right": ArrowLongRightIcon,
  "arrow-long-up": ArrowLongUpIcon,
  "arrow-path": ArrowPathIcon,
  "arrow-path-rounded-square": ArrowPathRoundedSquareIcon,
  "arrow-right": ArrowRightIcon,
  "arrow-right-circle": ArrowRightCircleIcon,
  "arrow-right-end-on-rectangle": ArrowRightEndOnRectangleIcon,
  "arrow-right-start-on-rectangle": ArrowRightStartOnRectangleIcon,
  "arrow-top-right-on-square": ArrowTopRightOnSquareIcon,
  "arrow-trending-down": ArrowTrendingDownIcon,
  "arrow-trending-up": ArrowTrendingUpIcon,
  "arrow-turn-down-left": ArrowTurnDownLeftIcon,
  "arrow-turn-down-right": ArrowTurnDownRightIcon,
  "arrow-turn-left-down": ArrowTurnLeftDownIcon,
  "arrow-turn-left-up": ArrowTurnLeftUpIcon,
  "arrow-turn-right-down": ArrowTurnRightDownIcon,
  "arrow-turn-right-up": ArrowTurnRightUpIcon,
  "arrow-turn-up-left": ArrowTurnUpLeftIcon,
  "arrow-turn-up-right": ArrowTurnUpRightIcon,
  "arrow-up": ArrowUpIcon,
  "arrow-up-circle": ArrowUpCircleIcon,
  "arrow-up-left": ArrowUpLeftIcon,
  "arrow-up-on-square": ArrowUpOnSquareIcon,
  "arrow-up-on-square-stack": ArrowUpOnSquareStackIcon,
  "arrow-up-right": ArrowUpRightIcon,
  "arrow-up-tray": ArrowUpTrayIcon,
  "arrow-uturn-down": ArrowUturnDownIcon,
  "arrow-uturn-left": ArrowUturnLeftIcon,
  "arrow-uturn-right": ArrowUturnRightIcon,
  "arrow-uturn-up": ArrowUturnUpIcon,
  "arrows-pointing-in": ArrowsPointingInIcon,
  "arrows-pointing-out": ArrowsPointingOutIcon,
  "arrows-right-left": ArrowsRightLeftIcon,
  "arrows-up-down": ArrowsUpDownIcon,
  "at-symbol": AtSymbolIcon,
  backspace: BackspaceIcon,
  backward: BackwardIcon,
  banknotes: BanknotesIcon,
  "bars-2": Bars2Icon,
  "bars-3": Bars3Icon,
  "bars-3-bottom-left": Bars3BottomLeftIcon,
  "bars-3-bottom-right": Bars3BottomRightIcon,
  "bars-3-center-left": Bars3CenterLeftIcon,
  "bars-4": Bars4Icon,
  "bars-arrow-down": BarsArrowDownIcon,
  "bars-arrow-up": BarsArrowUpIcon,
  "battery-0": Battery0Icon,
  "battery-100": Battery100Icon,
  "battery-50": Battery50Icon,
  beaker: BeakerIcon,
  bell: BellIcon,
  "bell-alert": BellAlertIcon,
  "bell-slash": BellSlashIcon,
  "bell-snooze": BellSnoozeIcon,
  bold: BoldIcon,
  bolt: BoltIcon,
  "bolt-slash": BoltSlashIcon,
  "book-open": BookOpenIcon,
  bookmark: BookmarkIcon,
  "bookmark-slash": BookmarkSlashIcon,
  "bookmark-square": BookmarkSquareIcon,
  briefcase: BriefcaseIcon,
  "bug-ant": BugAntIcon,
  "building-library": BuildingLibraryIcon,
  "building-office": BuildingOfficeIcon,
  "building-office-2": BuildingOffice2Icon,
  "building-storefront": BuildingStorefrontIcon,
  cake: CakeIcon,
  calculator: CalculatorIcon,
  calendar: CalendarIcon,
  "calendar-date-range": CalendarDateRangeIcon,
  "calendar-days": CalendarDaysIcon,
  camera: CameraIcon,
  "chart-bar": ChartBarIcon,
  "chart-bar-square": ChartBarSquareIcon,
  "chart-pie": ChartPieIcon,
  "chat-bubble-bottom-center": ChatBubbleBottomCenterIcon,
  "chat-bubble-bottom-center-text": ChatBubbleBottomCenterTextIcon,
  "chat-bubble-left": ChatBubbleLeftIcon,
  "chat-bubble-left-ellipsis": ChatBubbleLeftEllipsisIcon,
  "chat-bubble-left-right": ChatBubbleLeftRightIcon,
  "chat-bubble-oval-left": ChatBubbleOvalLeftIcon,
  "chat-bubble-oval-left-ellipsis": ChatBubbleOvalLeftEllipsisIcon,
  check: CheckIcon,
  "check-badge": CheckBadgeIcon,
  "check-circle": CheckCircleIcon,
  "chevron-double-down": ChevronDoubleDownIcon,
  "chevron-double-left": ChevronDoubleLeftIcon,
  "chevron-double-right": ChevronDoubleRightIcon,
  "chevron-double-up": ChevronDoubleUpIcon,
  "chevron-down": ChevronDownIcon,
  "chevron-left": ChevronLeftIcon,
  "chevron-right": ChevronRightIcon,
  "chevron-up": ChevronUpIcon,
  "chevron-up-down": ChevronUpDownIcon,
  "circle-stack": CircleStackIcon,
  clipboard: ClipboardIcon,
  "clipboard-document": ClipboardDocumentIcon,
  "clipboard-document-check": ClipboardDocumentCheckIcon,
  "clipboard-document-list": ClipboardDocumentListIcon,
  clock: ClockIcon,
  cloud: CloudIcon,
  "cloud-arrow-down": CloudArrowDownIcon,
  "cloud-arrow-up": CloudArrowUpIcon,
  "code-bracket": CodeBracketIcon,
  "code-bracket-square": CodeBracketSquareIcon,
  cog: CogIcon,
  "cog-6-tooth": Cog6ToothIcon,
  "cog-8-tooth": Cog8ToothIcon,
  "command-line": CommandLineIcon,
  "computer-desktop": ComputerDesktopIcon,
  "cpu-chip": CpuChipIcon,
  "credit-card": CreditCardIcon,
  cube: CubeIcon,
  "cube-transparent": CubeTransparentIcon,
  "currency-bangladeshi": CurrencyBangladeshiIcon,
  "currency-dollar": CurrencyDollarIcon,
  "currency-euro": CurrencyEuroIcon,
  "currency-pound": CurrencyPoundIcon,
  "currency-rupee": CurrencyRupeeIcon,
  "currency-yen": CurrencyYenIcon,
  "cursor-arrow-rays": CursorArrowRaysIcon,
  "cursor-arrow-ripple": CursorArrowRippleIcon,
  "device-phone-mobile": DevicePhoneMobileIcon,
  "device-tablet": DeviceTabletIcon,
  divide: DivideIcon,
  document: DocumentIcon,
  "document-arrow-down": DocumentArrowDownIcon,
  "document-arrow-up": DocumentArrowUpIcon,
  "document-chart-bar": DocumentChartBarIcon,
  "document-check": DocumentCheckIcon,
  "document-currency-bangladeshi": DocumentCurrencyBangladeshiIcon,
  "document-currency-dollar": DocumentCurrencyDollarIcon,
  "document-currency-euro": DocumentCurrencyEuroIcon,
  "document-currency-pound": DocumentCurrencyPoundIcon,
  "document-currency-rupee": DocumentCurrencyRupeeIcon,
  "document-currency-yen": DocumentCurrencyYenIcon,
  "document-duplicate": DocumentDuplicateIcon,
  "document-magnifying-glass": DocumentMagnifyingGlassIcon,
  "document-minus": DocumentMinusIcon,
  "document-plus": DocumentPlusIcon,
  "document-text": DocumentTextIcon,
  "ellipsis-horizontal": EllipsisHorizontalIcon,
  "ellipsis-horizontal-circle": EllipsisHorizontalCircleIcon,
  "ellipsis-vertical": EllipsisVerticalIcon,
  envelope: EnvelopeIcon,
  "envelope-open": EnvelopeOpenIcon,
  equals: EqualsIcon,
  "exclamation-circle": ExclamationCircleIcon,
  "exclamation-triangle": ExclamationTriangleIcon,
  eye: EyeIcon,
  "eye-dropper": EyeDropperIcon,
  "eye-slash": EyeSlashIcon,
  "face-frown": FaceFrownIcon,
  "face-smile": FaceSmileIcon,
  film: FilmIcon,
  "finger-print": FingerPrintIcon,
  fire: FireIcon,
  flag: FlagIcon,
  folder: FolderIcon,
  "folder-arrow-down": FolderArrowDownIcon,
  "folder-minus": FolderMinusIcon,
  "folder-open": FolderOpenIcon,
  "folder-plus": FolderPlusIcon,
  forward: ForwardIcon,
  funnel: FunnelIcon,
  gif: GifIcon,
  gift: GiftIcon,
  "gift-top": GiftTopIcon,
  "globe-alt": GlobeAltIcon,
  "globe-americas": GlobeAmericasIcon,
  "globe-asia-australia": GlobeAsiaAustraliaIcon,
  "globe-europe-africa": GlobeEuropeAfricaIcon,
  h1: H1Icon,
  h2: H2Icon,
  h3: H3Icon,
  "hand-raised": HandRaisedIcon,
  "hand-thumb-down": HandThumbDownIcon,
  "hand-thumb-up": HandThumbUpIcon,
  hashtag: HashtagIcon,
  heart: HeartIcon,
  home: HomeIcon,
  "home-modern": HomeModernIcon,
  identification: IdentificationIcon,
  inbox: InboxIcon,
  "inbox-arrow-down": InboxArrowDownIcon,
  "inbox-stack": InboxStackIcon,
  "information-circle": InformationCircleIcon,
  italic: ItalicIcon,
  key: KeyIcon,
  language: LanguageIcon,
  lifebuoy: LifebuoyIcon,
  "light-bulb": LightBulbIcon,
  link: LinkIcon,
  "link-slash": LinkSlashIcon,
  "list-bullet": ListBulletIcon,
  "lock-closed": LockClosedIcon,
  "lock-open": LockOpenIcon,
  "magnifying-glass": MagnifyingGlassIcon,
  "magnifying-glass-circle": MagnifyingGlassCircleIcon,
  "magnifying-glass-minus": MagnifyingGlassMinusIcon,
  "magnifying-glass-plus": MagnifyingGlassPlusIcon,
  map: MapIcon,
  "map-pin": MapPinIcon,
  megaphone: MegaphoneIcon,
  microphone: MicrophoneIcon,
  minus: MinusIcon,
  "minus-circle": MinusCircleIcon,
  moon: MoonIcon,
  "musical-note": MusicalNoteIcon,
  newspaper: NewspaperIcon,
  "no-symbol": NoSymbolIcon,
  "numbered-list": NumberedListIcon,
  "paint-brush": PaintBrushIcon,
  "paper-airplane": PaperAirplaneIcon,
  "paper-clip": PaperClipIcon,
  pause: PauseIcon,
  "pause-circle": PauseCircleIcon,
  pencil: PencilIcon,
  "pencil-square": PencilSquareIcon,
  "percent-badge": PercentBadgeIcon,
  phone: PhoneIcon,
  "phone-arrow-down-left": PhoneArrowDownLeftIcon,
  "phone-arrow-up-right": PhoneArrowUpRightIcon,
  "phone-x-mark": PhoneXMarkIcon,
  photo: PhotoIcon,
  play: PlayIcon,
  "play-circle": PlayCircleIcon,
  "play-pause": PlayPauseIcon,
  plus: PlusIcon,
  "plus-circle": PlusCircleIcon,
  power: PowerIcon,
  "presentation-chart-bar": PresentationChartBarIcon,
  "presentation-chart-line": PresentationChartLineIcon,
  printer: PrinterIcon,
  "puzzle-piece": PuzzlePieceIcon,
  "qr-code": QrCodeIcon,
  "question-mark-circle": QuestionMarkCircleIcon,
  "queue-list": QueueListIcon,
  radio: RadioIcon,
  "receipt-percent": ReceiptPercentIcon,
  "receipt-refund": ReceiptRefundIcon,
  "rectangle-group": RectangleGroupIcon,
  "rectangle-stack": RectangleStackIcon,
  "rocket-launch": RocketLaunchIcon,
  rss: RssIcon,
  scale: ScaleIcon,
  scissors: ScissorsIcon,
  server: ServerIcon,
  "server-stack": ServerStackIcon,
  share: ShareIcon,
  "shield-check": ShieldCheckIcon,
  "shield-exclamation": ShieldExclamationIcon,
  "shopping-bag": ShoppingBagIcon,
  "shopping-cart": ShoppingCartIcon,
  signal: SignalIcon,
  "signal-slash": SignalSlashIcon,
  slash: SlashIcon,
  sparkles: SparklesIcon,
  "speaker-wave": SpeakerWaveIcon,
  "speaker-x-mark": SpeakerXMarkIcon,
  "square-2-stack": Square2StackIcon,
  "square-3-stack-3d": Square3Stack3dIcon,
  "squares-2x2": Squares2x2Icon,
  "squares-plus": SquaresPlusIcon,
  star: StarIcon,
  stop: StopIcon,
  "stop-circle": StopCircleIcon,
  strikethrough: StrikethroughIcon,
  sun: SunIcon,
  swatch: SwatchIcon,
  "table-cells": TableCellsIcon,
  tag: TagIcon,
  ticket: TicketIcon,
  trash: TrashIcon,
  trophy: TrophyIcon,
  truck: TruckIcon,
  tv: TvIcon,
  underline: UnderlineIcon,
  user: UserIcon,
  "user-circle": UserCircleIcon,
  "user-group": UserGroupIcon,
  "user-minus": UserMinusIcon,
  "user-plus": UserPlusIcon,
  users: UsersIcon,
  variable: VariableIcon,
  "video-camera": VideoCameraIcon,
  "video-camera-slash": VideoCameraSlashIcon,
  "view-columns": ViewColumnsIcon,
  "viewfinder-circle": ViewfinderCircleIcon,
  wallet: WalletIcon,
  wifi: WifiIcon,
  window: WindowIcon,
  wrench: WrenchIcon,
  "wrench-screwdriver": WrenchScrewdriverIcon,
  "x-circle": XCircleIcon,
  "x-mark": XMarkIcon,
};
