// Auto-generated icon manifest - do not edit manually

export interface IconManifest {
  name: string;
  keywords: string[];
}

export const ICON_MANIFEST: IconManifest[] = [
  { name: "academic-cap", keywords: ["academic", "cap"] },
  { name: "adjustments-horizontal", keywords: ["adjustments", "horizontal"] },
  { name: "adjustments-vertical", keywords: ["adjustments", "vertical"] },
  { name: "archive-box", keywords: ["archive", "box"] },
  {
    name: "archive-box-arrow-down",
    keywords: ["archive", "box", "arrow", "down"],
  },
  { name: "archive-box-x-mark", keywords: ["archive", "box", "x", "mark"] },
  { name: "arrow-down", keywords: ["arrow", "down"] },
  { name: "arrow-down-circle", keywords: ["arrow", "down", "circle"] },
  { name: "arrow-down-left", keywords: ["arrow", "down", "left"] },
  { name: "arrow-down-on-square", keywords: ["arrow", "down", "on", "square"] },
  {
    name: "arrow-down-on-square-stack",
    keywords: ["arrow", "down", "on", "square", "stack"],
  },
  { name: "arrow-down-right", keywords: ["arrow", "down", "right"] },
  { name: "arrow-down-tray", keywords: ["arrow", "down", "tray"] },
  { name: "arrow-left", keywords: ["arrow", "left"] },
  { name: "arrow-left-circle", keywords: ["arrow", "left", "circle"] },
  {
    name: "arrow-left-end-on-rectangle",
    keywords: ["arrow", "left", "end", "on", "rectangle"],
  },
  {
    name: "arrow-left-start-on-rectangle",
    keywords: ["arrow", "left", "start", "on", "rectangle"],
  },
  { name: "arrow-long-down", keywords: ["arrow", "long", "down"] },
  { name: "arrow-long-left", keywords: ["arrow", "long", "left"] },
  { name: "arrow-long-right", keywords: ["arrow", "long", "right"] },
  { name: "arrow-long-up", keywords: ["arrow", "long", "up"] },
  { name: "arrow-path", keywords: ["arrow", "path"] },
  {
    name: "arrow-path-rounded-square",
    keywords: ["arrow", "path", "rounded", "square"],
  },
  { name: "arrow-right", keywords: ["arrow", "right"] },
  { name: "arrow-right-circle", keywords: ["arrow", "right", "circle"] },
  {
    name: "arrow-right-end-on-rectangle",
    keywords: ["arrow", "right", "end", "on", "rectangle"],
  },
  {
    name: "arrow-right-start-on-rectangle",
    keywords: ["arrow", "right", "start", "on", "rectangle"],
  },
  {
    name: "arrow-top-right-on-square",
    keywords: ["arrow", "top", "right", "on", "square"],
  },
  { name: "arrow-trending-down", keywords: ["arrow", "trending", "down"] },
  { name: "arrow-trending-up", keywords: ["arrow", "trending", "up"] },
  { name: "arrow-turn-down-left", keywords: ["arrow", "turn", "down", "left"] },
  {
    name: "arrow-turn-down-right",
    keywords: ["arrow", "turn", "down", "right"],
  },
  { name: "arrow-turn-left-down", keywords: ["arrow", "turn", "left", "down"] },
  { name: "arrow-turn-left-up", keywords: ["arrow", "turn", "left", "up"] },
  {
    name: "arrow-turn-right-down",
    keywords: ["arrow", "turn", "right", "down"],
  },
  { name: "arrow-turn-right-up", keywords: ["arrow", "turn", "right", "up"] },
  { name: "arrow-turn-up-left", keywords: ["arrow", "turn", "up", "left"] },
  { name: "arrow-turn-up-right", keywords: ["arrow", "turn", "up", "right"] },
  { name: "arrow-up", keywords: ["arrow", "up"] },
  { name: "arrow-up-circle", keywords: ["arrow", "up", "circle"] },
  { name: "arrow-up-left", keywords: ["arrow", "up", "left"] },
  { name: "arrow-up-on-square", keywords: ["arrow", "up", "on", "square"] },
  {
    name: "arrow-up-on-square-stack",
    keywords: ["arrow", "up", "on", "square", "stack"],
  },
  { name: "arrow-up-right", keywords: ["arrow", "up", "right"] },
  { name: "arrow-up-tray", keywords: ["arrow", "up", "tray"] },
  { name: "arrow-uturn-down", keywords: ["arrow", "uturn", "down"] },
  { name: "arrow-uturn-left", keywords: ["arrow", "uturn", "left"] },
  { name: "arrow-uturn-right", keywords: ["arrow", "uturn", "right"] },
  { name: "arrow-uturn-up", keywords: ["arrow", "uturn", "up"] },
  { name: "arrows-pointing-in", keywords: ["arrows", "pointing", "in"] },
  { name: "arrows-pointing-out", keywords: ["arrows", "pointing", "out"] },
  { name: "arrows-right-left", keywords: ["arrows", "right", "left"] },
  { name: "arrows-up-down", keywords: ["arrows", "up", "down"] },
  { name: "at-symbol", keywords: ["at", "symbol"] },
  { name: "backspace", keywords: ["backspace"] },
  { name: "backward", keywords: ["backward"] },
  { name: "banknotes", keywords: ["banknotes"] },
  { name: "bars-2", keywords: ["bars", "2"] },
  { name: "bars-3", keywords: ["bars", "3"] },
  { name: "bars-3-bottom-left", keywords: ["bars", "3", "bottom", "left"] },
  { name: "bars-3-bottom-right", keywords: ["bars", "3", "bottom", "right"] },
  { name: "bars-3-center-left", keywords: ["bars", "3", "center", "left"] },
  { name: "bars-4", keywords: ["bars", "4"] },
  { name: "bars-arrow-down", keywords: ["bars", "arrow", "down"] },
  { name: "bars-arrow-up", keywords: ["bars", "arrow", "up"] },
  { name: "battery-0", keywords: ["battery", "0"] },
  { name: "battery-100", keywords: ["battery", "100"] },
  { name: "battery-50", keywords: ["battery", "50"] },
  { name: "beaker", keywords: ["beaker"] },
  { name: "bell", keywords: ["bell"] },
  { name: "bell-alert", keywords: ["bell", "alert"] },
  { name: "bell-slash", keywords: ["bell", "slash"] },
  { name: "bell-snooze", keywords: ["bell", "snooze"] },
  { name: "bold", keywords: ["bold"] },
  { name: "bolt", keywords: ["bolt"] },
  { name: "bolt-slash", keywords: ["bolt", "slash"] },
  { name: "book-open", keywords: ["book", "open"] },
  { name: "bookmark", keywords: ["bookmark"] },
  { name: "bookmark-slash", keywords: ["bookmark", "slash"] },
  { name: "bookmark-square", keywords: ["bookmark", "square"] },
  { name: "briefcase", keywords: ["briefcase"] },
  { name: "bug-ant", keywords: ["bug", "ant"] },
  { name: "building-library", keywords: ["building", "library"] },
  { name: "building-office", keywords: ["building", "office"] },
  { name: "building-office-2", keywords: ["building", "office", "2"] },
  { name: "building-storefront", keywords: ["building", "storefront"] },
  { name: "cake", keywords: ["cake"] },
  { name: "calculator", keywords: ["calculator"] },
  { name: "calendar", keywords: ["calendar"] },
  { name: "calendar-date-range", keywords: ["calendar", "date", "range"] },
  { name: "calendar-days", keywords: ["calendar", "days"] },
  { name: "camera", keywords: ["camera"] },
  { name: "chart-bar", keywords: ["chart", "bar"] },
  { name: "chart-bar-square", keywords: ["chart", "bar", "square"] },
  { name: "chart-pie", keywords: ["chart", "pie"] },
  {
    name: "chat-bubble-bottom-center",
    keywords: ["chat", "bubble", "bottom", "center"],
  },
  {
    name: "chat-bubble-bottom-center-text",
    keywords: ["chat", "bubble", "bottom", "center", "text"],
  },
  { name: "chat-bubble-left", keywords: ["chat", "bubble", "left"] },
  {
    name: "chat-bubble-left-ellipsis",
    keywords: ["chat", "bubble", "left", "ellipsis"],
  },
  {
    name: "chat-bubble-left-right",
    keywords: ["chat", "bubble", "left", "right"],
  },
  {
    name: "chat-bubble-oval-left",
    keywords: ["chat", "bubble", "oval", "left"],
  },
  {
    name: "chat-bubble-oval-left-ellipsis",
    keywords: ["chat", "bubble", "oval", "left", "ellipsis"],
  },
  { name: "check", keywords: ["check"] },
  { name: "check-badge", keywords: ["check", "badge"] },
  { name: "check-circle", keywords: ["check", "circle"] },
  { name: "chevron-double-down", keywords: ["chevron", "double", "down"] },
  { name: "chevron-double-left", keywords: ["chevron", "double", "left"] },
  { name: "chevron-double-right", keywords: ["chevron", "double", "right"] },
  { name: "chevron-double-up", keywords: ["chevron", "double", "up"] },
  { name: "chevron-down", keywords: ["chevron", "down"] },
  { name: "chevron-left", keywords: ["chevron", "left"] },
  { name: "chevron-right", keywords: ["chevron", "right"] },
  { name: "chevron-up", keywords: ["chevron", "up"] },
  { name: "chevron-up-down", keywords: ["chevron", "up", "down"] },
  { name: "circle-stack", keywords: ["circle", "stack"] },
  { name: "clipboard", keywords: ["clipboard"] },
  { name: "clipboard-document", keywords: ["clipboard", "document"] },
  {
    name: "clipboard-document-check",
    keywords: ["clipboard", "document", "check"],
  },
  {
    name: "clipboard-document-list",
    keywords: ["clipboard", "document", "list"],
  },
  { name: "clock", keywords: ["clock"] },
  { name: "cloud", keywords: ["cloud"] },
  { name: "cloud-arrow-down", keywords: ["cloud", "arrow", "down"] },
  { name: "cloud-arrow-up", keywords: ["cloud", "arrow", "up"] },
  { name: "code-bracket", keywords: ["code", "bracket"] },
  { name: "code-bracket-square", keywords: ["code", "bracket", "square"] },
  { name: "cog", keywords: ["cog"] },
  { name: "cog-6-tooth", keywords: ["cog", "6", "tooth"] },
  { name: "cog-8-tooth", keywords: ["cog", "8", "tooth"] },
  { name: "command-line", keywords: ["command", "line"] },
  { name: "computer-desktop", keywords: ["computer", "desktop"] },
  { name: "cpu-chip", keywords: ["cpu", "chip"] },
  { name: "credit-card", keywords: ["credit", "card"] },
  { name: "cube", keywords: ["cube"] },
  { name: "cube-transparent", keywords: ["cube", "transparent"] },
  { name: "currency-bangladeshi", keywords: ["currency", "bangladeshi"] },
  { name: "currency-dollar", keywords: ["currency", "dollar"] },
  { name: "currency-euro", keywords: ["currency", "euro"] },
  { name: "currency-pound", keywords: ["currency", "pound"] },
  { name: "currency-rupee", keywords: ["currency", "rupee"] },
  { name: "currency-yen", keywords: ["currency", "yen"] },
  { name: "cursor-arrow-rays", keywords: ["cursor", "arrow", "rays"] },
  { name: "cursor-arrow-ripple", keywords: ["cursor", "arrow", "ripple"] },
  { name: "device-phone-mobile", keywords: ["device", "phone", "mobile"] },
  { name: "device-tablet", keywords: ["device", "tablet"] },
  { name: "divide", keywords: ["divide"] },
  { name: "document", keywords: ["document"] },
  { name: "document-arrow-down", keywords: ["document", "arrow", "down"] },
  { name: "document-arrow-up", keywords: ["document", "arrow", "up"] },
  { name: "document-chart-bar", keywords: ["document", "chart", "bar"] },
  { name: "document-check", keywords: ["document", "check"] },
  {
    name: "document-currency-bangladeshi",
    keywords: ["document", "currency", "bangladeshi"],
  },
  {
    name: "document-currency-dollar",
    keywords: ["document", "currency", "dollar"],
  },
  {
    name: "document-currency-euro",
    keywords: ["document", "currency", "euro"],
  },
  {
    name: "document-currency-pound",
    keywords: ["document", "currency", "pound"],
  },
  {
    name: "document-currency-rupee",
    keywords: ["document", "currency", "rupee"],
  },
  { name: "document-currency-yen", keywords: ["document", "currency", "yen"] },
  { name: "document-duplicate", keywords: ["document", "duplicate"] },
  {
    name: "document-magnifying-glass",
    keywords: ["document", "magnifying", "glass"],
  },
  { name: "document-minus", keywords: ["document", "minus"] },
  { name: "document-plus", keywords: ["document", "plus"] },
  { name: "document-text", keywords: ["document", "text"] },
  { name: "ellipsis-horizontal", keywords: ["ellipsis", "horizontal"] },
  {
    name: "ellipsis-horizontal-circle",
    keywords: ["ellipsis", "horizontal", "circle"],
  },
  { name: "ellipsis-vertical", keywords: ["ellipsis", "vertical"] },
  { name: "envelope", keywords: ["envelope"] },
  { name: "envelope-open", keywords: ["envelope", "open"] },
  { name: "equals", keywords: ["equals"] },
  { name: "exclamation-circle", keywords: ["exclamation", "circle"] },
  { name: "exclamation-triangle", keywords: ["exclamation", "triangle"] },
  { name: "eye", keywords: ["eye"] },
  { name: "eye-dropper", keywords: ["eye", "dropper"] },
  { name: "eye-slash", keywords: ["eye", "slash"] },
  { name: "face-frown", keywords: ["face", "frown"] },
  { name: "face-smile", keywords: ["face", "smile"] },
  { name: "film", keywords: ["film"] },
  { name: "finger-print", keywords: ["finger", "print"] },
  { name: "fire", keywords: ["fire"] },
  { name: "flag", keywords: ["flag"] },
  { name: "folder", keywords: ["folder"] },
  { name: "folder-arrow-down", keywords: ["folder", "arrow", "down"] },
  { name: "folder-minus", keywords: ["folder", "minus"] },
  { name: "folder-open", keywords: ["folder", "open"] },
  { name: "folder-plus", keywords: ["folder", "plus"] },
  { name: "forward", keywords: ["forward"] },
  { name: "funnel", keywords: ["funnel"] },
  { name: "gif", keywords: ["gif"] },
  { name: "gift", keywords: ["gift"] },
  { name: "gift-top", keywords: ["gift", "top"] },
  { name: "globe-alt", keywords: ["globe", "alt"] },
  { name: "globe-americas", keywords: ["globe", "americas"] },
  { name: "globe-asia-australia", keywords: ["globe", "asia", "australia"] },
  { name: "globe-europe-africa", keywords: ["globe", "europe", "africa"] },
  { name: "h1", keywords: ["h1"] },
  { name: "h2", keywords: ["h2"] },
  { name: "h3", keywords: ["h3"] },
  { name: "hand-raised", keywords: ["hand", "raised"] },
  { name: "hand-thumb-down", keywords: ["hand", "thumb", "down"] },
  { name: "hand-thumb-up", keywords: ["hand", "thumb", "up"] },
  { name: "hashtag", keywords: ["hashtag"] },
  { name: "heart", keywords: ["heart"] },
  { name: "home", keywords: ["home"] },
  { name: "home-modern", keywords: ["home", "modern"] },
  { name: "identification", keywords: ["identification"] },
  { name: "inbox", keywords: ["inbox"] },
  { name: "inbox-arrow-down", keywords: ["inbox", "arrow", "down"] },
  { name: "inbox-stack", keywords: ["inbox", "stack"] },
  { name: "information-circle", keywords: ["information", "circle"] },
  { name: "italic", keywords: ["italic"] },
  { name: "key", keywords: ["key"] },
  { name: "language", keywords: ["language"] },
  { name: "lifebuoy", keywords: ["lifebuoy"] },
  { name: "light-bulb", keywords: ["light", "bulb"] },
  { name: "link", keywords: ["link"] },
  { name: "link-slash", keywords: ["link", "slash"] },
  { name: "list-bullet", keywords: ["list", "bullet"] },
  { name: "lock-closed", keywords: ["lock", "closed"] },
  { name: "lock-open", keywords: ["lock", "open"] },
  { name: "magnifying-glass", keywords: ["magnifying", "glass"] },
  {
    name: "magnifying-glass-circle",
    keywords: ["magnifying", "glass", "circle"],
  },
  {
    name: "magnifying-glass-minus",
    keywords: ["magnifying", "glass", "minus"],
  },
  { name: "magnifying-glass-plus", keywords: ["magnifying", "glass", "plus"] },
  { name: "map", keywords: ["map"] },
  { name: "map-pin", keywords: ["map", "pin"] },
  { name: "megaphone", keywords: ["megaphone"] },
  { name: "microphone", keywords: ["microphone"] },
  { name: "minus", keywords: ["minus"] },
  { name: "minus-circle", keywords: ["minus", "circle"] },
  { name: "moon", keywords: ["moon"] },
  { name: "musical-note", keywords: ["musical", "note"] },
  { name: "newspaper", keywords: ["newspaper"] },
  { name: "no-symbol", keywords: ["no", "symbol"] },
  { name: "numbered-list", keywords: ["numbered", "list"] },
  { name: "paint-brush", keywords: ["paint", "brush"] },
  { name: "paper-airplane", keywords: ["paper", "airplane"] },
  { name: "paper-clip", keywords: ["paper", "clip"] },
  { name: "pause", keywords: ["pause"] },
  { name: "pause-circle", keywords: ["pause", "circle"] },
  { name: "pencil", keywords: ["pencil"] },
  { name: "pencil-square", keywords: ["pencil", "square"] },
  { name: "percent-badge", keywords: ["percent", "badge"] },
  { name: "phone", keywords: ["phone"] },
  {
    name: "phone-arrow-down-left",
    keywords: ["phone", "arrow", "down", "left"],
  },
  { name: "phone-arrow-up-right", keywords: ["phone", "arrow", "up", "right"] },
  { name: "phone-x-mark", keywords: ["phone", "x", "mark"] },
  { name: "photo", keywords: ["photo"] },
  { name: "play", keywords: ["play"] },
  { name: "play-circle", keywords: ["play", "circle"] },
  { name: "play-pause", keywords: ["play", "pause"] },
  { name: "plus", keywords: ["plus"] },
  { name: "plus-circle", keywords: ["plus", "circle"] },
  { name: "power", keywords: ["power"] },
  {
    name: "presentation-chart-bar",
    keywords: ["presentation", "chart", "bar"],
  },
  {
    name: "presentation-chart-line",
    keywords: ["presentation", "chart", "line"],
  },
  { name: "printer", keywords: ["printer"] },
  { name: "puzzle-piece", keywords: ["puzzle", "piece"] },
  { name: "qr-code", keywords: ["qr", "code"] },
  { name: "question-mark-circle", keywords: ["question", "mark", "circle"] },
  { name: "queue-list", keywords: ["queue", "list"] },
  { name: "radio", keywords: ["radio"] },
  { name: "receipt-percent", keywords: ["receipt", "percent"] },
  { name: "receipt-refund", keywords: ["receipt", "refund"] },
  { name: "rectangle-group", keywords: ["rectangle", "group"] },
  { name: "rectangle-stack", keywords: ["rectangle", "stack"] },
  { name: "rocket-launch", keywords: ["rocket", "launch"] },
  { name: "rss", keywords: ["rss"] },
  { name: "scale", keywords: ["scale"] },
  { name: "scissors", keywords: ["scissors"] },
  { name: "server", keywords: ["server"] },
  { name: "server-stack", keywords: ["server", "stack"] },
  { name: "share", keywords: ["share"] },
  { name: "shield-check", keywords: ["shield", "check"] },
  { name: "shield-exclamation", keywords: ["shield", "exclamation"] },
  { name: "shopping-bag", keywords: ["shopping", "bag"] },
  { name: "shopping-cart", keywords: ["shopping", "cart"] },
  { name: "signal", keywords: ["signal"] },
  { name: "signal-slash", keywords: ["signal", "slash"] },
  { name: "slash", keywords: ["slash"] },
  { name: "sparkles", keywords: ["sparkles"] },
  { name: "speaker-wave", keywords: ["speaker", "wave"] },
  { name: "speaker-x-mark", keywords: ["speaker", "x", "mark"] },
  { name: "square-2-stack", keywords: ["square", "2", "stack"] },
  { name: "square-3-stack-3d", keywords: ["square", "3", "stack", "3d"] },
  { name: "squares-2x2", keywords: ["squares", "2x2"] },
  { name: "squares-plus", keywords: ["squares", "plus"] },
  { name: "star", keywords: ["star"] },
  { name: "stop", keywords: ["stop"] },
  { name: "stop-circle", keywords: ["stop", "circle"] },
  { name: "strikethrough", keywords: ["strikethrough"] },
  { name: "sun", keywords: ["sun"] },
  { name: "swatch", keywords: ["swatch"] },
  { name: "table-cells", keywords: ["table", "cells"] },
  { name: "tag", keywords: ["tag"] },
  { name: "ticket", keywords: ["ticket"] },
  { name: "trash", keywords: ["trash"] },
  { name: "trophy", keywords: ["trophy"] },
  { name: "truck", keywords: ["truck"] },
  { name: "tv", keywords: ["tv"] },
  { name: "underline", keywords: ["underline"] },
  { name: "user", keywords: ["user"] },
  { name: "user-circle", keywords: ["user", "circle"] },
  { name: "user-group", keywords: ["user", "group"] },
  { name: "user-minus", keywords: ["user", "minus"] },
  { name: "user-plus", keywords: ["user", "plus"] },
  { name: "users", keywords: ["users"] },
  { name: "variable", keywords: ["variable"] },
  { name: "video-camera", keywords: ["video", "camera"] },
  { name: "video-camera-slash", keywords: ["video", "camera", "slash"] },
  { name: "view-columns", keywords: ["view", "columns"] },
  { name: "viewfinder-circle", keywords: ["viewfinder", "circle"] },
  { name: "wallet", keywords: ["wallet"] },
  { name: "wifi", keywords: ["wifi"] },
  { name: "window", keywords: ["window"] },
  { name: "wrench", keywords: ["wrench"] },
  { name: "wrench-screwdriver", keywords: ["wrench", "screwdriver"] },
  { name: "x-circle", keywords: ["x", "circle"] },
  { name: "x-mark", keywords: ["x", "mark"] },
];
